"""agregar drive_file_id y drive_url a videos_dataset

Revision ID: 443f4584dbfa
Revises: 
Create Date: 2026-08-16 20:05:34.977007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443f4584dbfa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos_dataset', sa.Column('drive_file_id', sa.String(length=200), nullable=True))
    op.add_column('videos_dataset', sa.Column('drive_url', sa.String(length=500), nullable=True))
    op.alter_column('videos_dataset', 'ruta_video',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.create_index(op.f('ix_videos_dataset_drive_file_id'), 'videos_dataset', ['drive_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_dataset_drive_file_id'), table_name='videos_dataset')
    op.alter_column('videos_dataset', 'ruta_video',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('videos_dataset', 'drive_url')
    op.drop_column('videos_dataset', 'drive_file_id')
    # ### end Alembic commands ###
